services:
    pico.reputation.notification.type.rate_post_positive:
        class: pico\reputation\notification\type\rate_post_positive
        shared: false
        parent: notification.type.base
        arguments:
            - '@user_loader'
            - '@cache.driver'
            - '@config'
            - '%tables.notification_types%'
            - '%tables.notifications%'
        tags:
            - { name: notification.type }

    pico.reputation.notification.type.rate_post_negative:
        class: pico\reputation\notification\type\rate_post_negative
        shared: false
        parent: notification.type.base
        arguments:
            - '@user_loader'
            - '@cache.driver'
            - '@config'
            - '%tables.notification_types%'
            - '%tables.notifications%'
        tags:
            - { name: notification.type }

    pico.reputation.notification.type.rate_user:
        class: pico\reputation\notification\type\rate_user
        shared: false
        parent: notification.type.base
        arguments:
            - '@user_loader'
            - '@cache.driver'
            - '@config'
            - '%tables.notification_types%'
            - '%tables.notifications%'
        tags:
            - { name: notification.type }
        tags:
            - { name: notification.type }
